### ISSUE TITLE
Add vcs feature

### ISSUE THREAD

**Issue by seokju-na** [seokju-na/geeks-diary#61]
## UI Sketch
![geeks-diary-git-planning](https://user-images.githubusercontent.com/13250888/47850783-c5dddb80-de19-11e8-9634-4bd442d04b8f.jpeg)

### Nov 5, 2018
![geeks-diary-vcs-architecting-1](https://user-images.githubusercontent.com/13250888/47999212-356b0800-e145-11e8-9e6a-778b940dc9f9.jpeg)

![UML](http://www.plantuml.com/plantuml/png/TO_VQZ8n4CNlzodcqeyFV00HiVY72bgAjb8efOp9Q5EpYMJ6BLBstUjcDsZRxKqWypipvvmX2mOvvZOxeDhZZc2jUE7rqHBq-zE0EGq6y9a1A8lC5LrHA8oYE0Ju3qoofDmNT1zyOJI5JhVR_TT0JK9AvbwX7RsXsn5t4jfHFRyrB3uOukizFZaLwOtJrNMXHCli_5o5hMbhP03Si0HKaj8dUOeQHN-mAIhnuTHYkJRqqMvukRL0TrQ7aSyFtf6JxtGcb2zmJw5UYvLHwyQohfhcAX0ALHiSGIyTU7w9chAzQKnPoNuxpmrBa-zdk-La_FZqEfhSFKoMvt9Z5DmWN_hvpJifWKBnIb0epj87UX08jNVs15jZQUQsdcFQQVEBYSkip8Raz36tNm00)

### UI
- [x] Tab #62
- [x] Checkbox #63
- [x] Expansion #64 
- [x] Menu #77 (Included)

### VCS
- [x] VcsRemoteService -> VcsService #66
- [x] Base vcs redux center (state / actions / reducer) #68 
- [x] Design algorithm for vcs item making factory. #71 
- ~Vcs list UI interaction.~ (Maybe I will do it later)
- [x] Vcs redux center. Including effects. #75 
- [x] Commit dialog #78 
- [x] History #86 
- [x] Sync with remote (pull/push) #90 

## Notes
- [x] Add note vcs item. #79
